### ISSUE TITLE
Create A Robust Logging System.

### ISSUE THREAD

**Issue by NavneetNayak** [acmpesuecc/cgc#1]
Currently the garbage collector does not log any information.
Propose a design for and write a logging module that prints out logs at various points of the garbage collection process, from allocating memory, starting of garbage collection process, freeing of memory and wherever else you feel is necessary.
The logs should be concise and print out relevant information about the current task being done. (like how much memory was allocated, how much was freed etc..)
The logging module should output to either STDOUT or STDERR based on user choice, and the user should have the choice to disable logging entirely if they desire (Logging should be disabled by default). 

Points will be given based on the proposal and implementation.

**Comment by eshwarRA** [comment]
please assign

**Comment by NavneetNayak** [comment]
!assign @eshwarRA

**Comment by NavneetNayak** [comment]
@eshwarRA please create a pr with current progress extension will be given based on that

**Comment by NavneetNayak** [comment]
!deassign @eshwarRA

**Comment by NavneetNayak** [comment]
@eshwarRA pls request again if you want to work on this or any other issue

**Comment by Ruchavw** [comment]
can I get this assigned?

**Comment by NavneetNayak** [comment]
@Ruchavw do you still want to work on this?

**Comment by Ruchavw** [comment]
yes @NavneetNayak

**Comment by NavneetNayak** [comment]
!assign @Ruchavw

**Comment by Ruchavw** [comment]
I haven't been assigned the problem @NavneetNayak

**Comment by NavneetNayak** [comment]
@Ruchavw you are probably assigned to some other issue please !withdraw from it

**Comment by Ruchavw** [comment]
Done


> @Ruchavw you are probably assigned to some other issue please !withdraw from it

Done

**Comment by NavneetNayak** [comment]
!assign @Ruchavw

**Comment by Ruchavw** [comment]
It still didn't get assigned to me @NavneetNayak

**Comment by Ruchavw** [comment]
> It still didn't get assigned to me @NavneetNayak

And I am not assigned any other questions right now

**Comment by NavneetNayak** [comment]
!assign @Ruchavw

**Comment by NavneetNayak** [comment]
!assign @Ruchavw

**Comment by NavneetNayak** [comment]
!assign @Ruchavw

**Comment by NavneetNayak** [comment]
@Ruchavw you can work on this

**Comment by Ruchavw** [comment]
> @Ruchavw you can work on this

Ok Thank you

**Comment by NavneetNayak** [comment]
!deassign @Ruchavw
