### ISSUE TITLE
Get Actual Page Size

### ISSUE THREAD

**Issue by NavneetNayak** [acmpesuecc/cgc#2]
Right now the garbage collector defines the size of a page of memory as `4096` bytes, as seen in  `gc.h` `#define PAGE_SIZE 4096`. This may not be true for all systems, the page size may differ, hence we need to get the actual page size of the system, make this correction.

**Comment by jhalak-n** [comment]
hi can you assign this to me

**Comment by NavneetNayak** [comment]
!assign @jhalak-n

**Comment by NavneetNayak** [comment]
sure go ahead

**Comment by jhalak-n** [comment]
!withdraw

**Comment by ayaanGH06** [comment]
Can i get assigned to this problem

**Comment by NavneetNayak** [comment]
@ayaanGH06 do you want to work on this?

**Comment by ayaanGH06** [comment]
@NavneetNayak  yes

**Comment by NavneetNayak** [comment]
!assign @ayaanGH06

**Comment by bwaklog** [comment]
!assign @ayaanGH06

**Comment by bwaklog** [comment]
!assign @ayaanGH06

**Comment by NavneetNayak** [comment]
@ayaanGH06 I am designing this issue from you

**Comment by NavneetNayak** [comment]
!deassign @ayaanGH06

**Comment by NavneetNayak** [comment]
!assign @ayaanGH06 15

**Comment by NavneetNayak** [comment]
!deassign @ayaanGH06

**Comment by DhruvHegde** [comment]
can i work on this

**Comment by DhruvHegde** [comment]
@NavneetNayak
