### ISSUE TITLE
Improve Initialization of Garbage Collector

### ISSUE THREAD

**Issue by NavneetNayak** [acmpesuecc/cgc#3]
Currently to initialize the allocator & garbage collector, we call the `alloc_init()` function, but we have to initialize the bottom of stack (`bos`) in function where we call `alloc_init()`. 
Also the `alloc_init()` function makes use of `malloc()` as well as the `mem_fetch()` function to allocate memory for itself and all the structures required by the allocator. This use of multiple different allocation functions is extremely messy for a couple reasons.
  a. Use of a the C standard library memory allocator functions such as `malloc()` to initialize our own allocator leads to two different memory allocators being used (including ours).
  b. The `mem_fetch()` function requests an arbitrary number of bytes using the `mmap()` system call, requesting anything other than a multiple of the memory page size (`PAGE_SIZE`) leads to slow `mmap()` calls

To improve the initialization of the garbage collector:
1. Move the setting of `bos` value to inside the `alloc_init()` function.
2. Remove all uses of `malloc()` and `mem_fetch()` , Exclusively use the `mempage_fetch()` function to fetch memory in pages, allocate enough memory for all the allocator structures manually, and add the remaining memory in the page to the free list.

**Comment by eshwarRA** [comment]
please assign

**Comment by KaparthyReddy** [comment]
Kindly assign this.

**Comment by NavneetNayak** [comment]
!assign @KaparthyReddy

**Comment by NavneetNayak** [comment]
@KaparthyReddy you can work on this

**Comment by NavneetNayak** [comment]
!deassign @KarpathyReddy

**Comment by NavneetNayak** [comment]
!assign @KarpathyReddy

**Comment by NavneetNayak** [comment]
!deassign @KaparthyReddy

**Comment by NavneetNayak** [comment]
@KaparthyReddy request here if you want to continue working on the issue

**Comment by Keeru-2005** [comment]
can i please get assigned to this? @NavneetNayak

**Comment by NavneetNayak** [comment]
!assign @Keeru-2005

**Comment by NavneetNayak** [comment]
@Keeru-2005 you are assigned to another issue please !withdraw then I can assign this issue to you

**Comment by Keeru-2005** [comment]
yes i have withdrawn from the other issue, please assign this to me @NavneetNayak

**Comment by NavneetNayak** [comment]
!assign @Keeru-2005

**Comment by NavneetNayak** [comment]
!deassign @Keeru-2005
