### ISSUE TITLE
Add Functionality To Start, Stop And Temporarily Pause Garbage Collection

### ISSUE THREAD

**Issue by NavneetNayak** [acmpesuecc/cgc#4]
Currently once the garbage collector is initialized using `alloc_init()` there is no way to stop or pause the garbage collection process. 
Add functionality to explicitly Start, Stop and Pause the garbage collection. The user should be able to perform any of these operations at any point.

**Comment by eshwarRA** [comment]
please assign

**Comment by RisuKumari11** [comment]
can i get assigned this

**Comment by NavneetNayak** [comment]
@RisuKumari11  do you still want to work on this

**Comment by RisuKumari11** [comment]
yes assign me

**Comment by NavneetNayak** [comment]
!assign @RisuKumari11

**Comment by NavneetNayak** [comment]
@RisuKumari11 you are assigned to some other issue please !withdraw from it to be assigned to this

**Comment by RisuKumari11** [comment]
withdrew

**Comment by NavneetNayak** [comment]
!assign @RisuKumari11

**Comment by NavneetNayak** [comment]
!assign @RisuKumari11

**Comment by NavneetNayak** [comment]
@RisuKumari11 you are assigned this issue

**Comment by NavneetNayak** [comment]
!deassign @RisuKumari11

**Comment by NavneetNayak** [comment]
!assign @KarpathyReddy

**Comment by NavneetNayak** [comment]
!deassign @KarpathyReddy

**Comment by Rxnnie-08** [comment]
Can I get assigned to this?

**Comment by NavneetNayak** [comment]
!assign @Rxnnie-08

**Comment by NavneetNayak** [comment]
@Rxnnie-08 please make a pr showing your progress if you want be extend on this issue

**Comment by NavneetNayak** [comment]
!deassign @Rxnnie-08

**Comment by KaparthyReddy** [comment]
kindly assign.

**Comment by NavneetNayak** [comment]
!assign @KaparthyReddy

**Comment by NavneetNayak** [comment]
!deassign @KaparthyReddy

**Comment by NavneetNayak** [comment]
@KaparthyReddy message here if u want to continue working on this issue

**Comment by VulcanRaven737** [comment]
Can I please get assigned to this?
