### ISSUE TITLE
Implement The `mem_calloc()` And `mem_realloc()` Functions

### ISSUE THREAD

**Issue by NavneetNayak** [acmpesuecc/cgc#5]
Currently the Allocator only has one function for memory allocation `mem_alloc()` which works similarly to the C Standard Library's `malloc()`.
Implement two new functions: `mem_calloc()` and `mem_realloc()`.
Both emulating the behavior of the C standard library's `calloc()` and `realloc()` respectively. You can read more about `calloc()` and `realloc()`, you can read their manual pages: `man calloc` or `man realloc`

**Comment by Ayush-jk** [comment]
can you assign this to me?

**Comment by NavneetNayak** [comment]
!assign Ayush-jk

**Comment by NavneetNayak** [comment]
!assign @Ayush-jk

**Comment by NavneetNayak** [comment]
@Ayush-jk go ahead

**Comment by Ayush-jk** [comment]
could u please assign this

**Comment by NavneetNayak** [comment]
!assign @Ayush-jk

**Comment by NavneetNayak** [comment]
@Ayush-jk if you are not getting assigned then you might be assigned to another issues plese withdraw from that if you wish to work on this

**Comment by Ayush-jk** [comment]
i did withdraw from there and un-assigned myself there.

**Comment by NavneetNayak** [comment]
!assign @Ayush-jk

**Comment by NavneetNayak** [comment]
Please check again are you sure you are not assigned to any other issue?

**Comment by Ayush-jk** [comment]
yes, I have checked it I am not assigned to any other issue.

**Comment by NavneetNayak** [comment]
!assign @Ayush-jk

**Comment by Anirudh10070** [comment]
please assign this

**Comment by NavneetNayak** [comment]
!assign @Anirudh10070

**Comment by prajwal-b-h** [comment]
can you assign me this

**Comment by NavneetNayak** [comment]
!assign @prajwal-b-h

**Comment by KaparthyReddy** [comment]
Kindly assign this.

**Comment by Anirudh10070** [comment]
please assign this to me

**Comment by AyushChakraborty** [comment]
please assign this to me

**Comment by NavneetNayak** [comment]
@AyushChakraborty do you still want to work on this?

**Comment by AyushChakraborty** [comment]
@NavneetNayak yes

**Comment by AyushChakraborty** [comment]
@NavneetNayak i will deassign myself from the other repo i was starting to work

**Comment by NavneetNayak** [comment]
sure

**Comment by NavneetNayak** [comment]
lmk when you have de-assigned yourself

**Comment by prajwal-b-h** [comment]
@NavneetNayak  deassign me

**Comment by AyushChakraborty** [comment]
@NavneetNayak i have deassigned from other one

**Comment by AyushChakraborty** [comment]
pls assign me here now

**Comment by NavneetNayak** [comment]
!assign @AyushChakraborty

**Comment by AyushChakraborty** [comment]
@NavneetNayak give me a bit more time, implementing mem_calloc() first

**Comment by NavneetNayak** [comment]
@AyushChakraborty please pr

**Comment by AyushChakraborty** [comment]
yes one sec

**Comment by AyushChakraborty** [comment]
@NavneetNayak done, for mem_calloc()

**Comment by NavneetNayak** [comment]
!deassign @AyushChakraborty

**Comment by NavneetNayak** [comment]
!assign @AyushChakraborty

**Comment by NavneetNayak** [comment]
!deassign @AyushChakraborty

**Comment by NavneetNayak** [comment]
solved in #10
